### ISSUE TITLE
Poor performance of key generation

### ISSUE THREAD

**Issue by imajeff** [JamesCullum/PGP-Anywhere#11]
After some debugging I have encountered issues with the secure random number generator from SJCL. Especially on older devices, it will take quite a lot of time to generate the required entropy, even for lower paranoia levels.

As a solution, I propose two solutions
- Indicate a progress of the entropy generator and instruct the user to move the mouse
- Use a different algorithm as secure random number generator, like `window.crypto.getRandomValues`

**Comment by JamesCullum** [comment]
Thank you very much!

Can you try the new options.js from [this commit](https://github.com/JamesCullum/PGP-Anywhere/commit/e64e3e0db9d21636f75477eae57175879ab4bf5f)?

If it works fine for you, I will push it for everyone.

**Comment by imajeff** [comment]
Ok I pasted the new options.js in the code and generating took about 2 seconds. So I guess it's great!

**Comment by JamesCullum** [comment]
Published as v4.0.2
