### ISSUE TITLE
error generating keys, cannot see any that were generated before

### ISSUE THREAD

**Issue by imajeff** [JamesCullum/PGP-Anywhere#15]
No keys are shown even if I had been using them long ago before this version of pgp anywhere
Generate new key shows error:
PGP Anywhere
CORRUPT: ccm: tag doesn't match

reinstall of extension only allows generating new key once but never shows if it saved it, then goes back to same error.

Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by JamesCullum** [comment]
Please click on "Delete all keys" and then try again. Try to not set a master password in the beginning.

**Comment by imajeff** [comment]
Thank you but why? It solved that but is this a bug? Seems like nobody would want their keys to ever be saved with no master password. Also, was there any way to recover all my keys I made years ago before I had to delete all of them?

**Comment by JamesCullum** [comment]
If you have a backup, you can restore keys from there, yes. Can you verify if, after emptying and saving without master password, adding a master password breaks it?

**Comment by imajeff** [comment]
Added a master password after it was working and it broke again

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by JamesCullum** [comment]
Good points, thanks a lot - will take a look at it 👍

**Comment by UnlimitedChild** [comment]
Hello,
I get an error: CORRUPT: ccm: tag doesn't match. This happens after I've generated my first key. After that, the key will not be added to the list of available keys. When I try to generate the key again, I get this error message.

**Comment by UnlimitedChild** [comment]
> Please click on "Delete all keys" and then try again. Try to not set a master password in the beginning.

This solution didn't work for me!

**Comment by JamesCullum** [comment]
If anyone can support the debugging and development, that'd be highly appreciated

**Comment by JamesCullum** [comment]
@UnlimitedChild Just handed in 5.0.2 with a potential bugfix - please test once you receive the update and let me know if it works. Locally I dont have any issues, even with a master password.

**Comment by UnlimitedChild** [comment]
> @UnlimitedChild Just handed in 5.0.2 with a potential bugfix - please test once you receive the update and let me know if it works. Locally I dont have any issues, even with a master password.

Thank you! I even got old keys that were not visible. Everything works for me now!
