### ISSUE TITLE
Export keys

### ISSUE THREAD

**Issue by JamesCullum** [JamesCullum/PGP-Anywhere#3]
It should be possible to export keys, both encrypted and unencrypted.

**Comment by darvvin** [comment]
Copy button or auto-select the text after encryption/decryption?

**Comment by JamesCullum** [comment]
I was thinking of changing the "Save" Button to a dropdown. Public keys will be exported as a downloadable file (.asc), for private keys you can choose between an unsafe file (key + password in cleartext with warning) or an encrypted copy.
