### ISSUE TITLE
Error decrypting private key: Cannot read property 'decrypt' of undefined

### ISSUE THREAD

**Issue by jscott0** [JamesCullum/PGP-Anywhere#6]
After completing a successful installation of PGP Anywhere on Google Chrome, I imported my keypair and attempted to make use of it. Encryption and signing using my public key seem to be fine. However, when using my private key and attempting to "Sign" or "Decrypt" any message throws the error:
`Error: Error decrypting private key: Cannot read property 'decrypt' of undefined`

**Comment by jscott0** [comment]
I have updated my version of Google Chrome, readded my key, and the issue went away. It seems to be a problem on my part (though I do not know what it could have been).

**Comment by JamesCullum** [comment]
Thank you for the report! Could it have been a typo?
